/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Logic.Alumno;
import Logic.Control;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Brigels Pacheco
 */
public class vistaPrincipal extends javax.swing.JFrame {
    
    private ArrayList<Alumno> dB = new ArrayList<>();
    
    
    //CREATOR
    public vistaPrincipal() {
        
        //quitarle los botones de arriba
        vistaPrincipal.super.setUndecorated(true);

        //color de fondo
        this.getContentPane().setBackground(Color.decode( "#FFFFFF"));

        //centrarlo
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        setSize(height - (height / 3), width - ( 14 * width / 24));
        setLocationRelativeTo(null);
//        setVisible(true);

        initComponents();

        //desabilitar el carnet
        txtCarnet.setVisible(false);
        lblCarnet.setVisible(false);

        //desabilitar warning.
        lblWarning.setVisible(false);
        //ubicar el foco en el inicio
        txtNombre.requestFocus();

        //boton agregar seleccionado desde el inicio
        rbtnAgregar.setSelected(true);

        //imagen de icono
        ImageIcon fot = new ImageIcon("src/imagenes/estudiante-icono.png");
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(imagen.getWidth(), imagen.getHeight(), Image.SCALE_DEFAULT));
        imagen.setIcon(icono);
        this.repaint();

      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngOpciones = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rbtnAgregar = new javax.swing.JRadioButton();
        rbtnBuscar = new javax.swing.JRadioButton();
        rbtnEditar = new javax.swing.JRadioButton();
        rbtnEliminar = new javax.swing.JRadioButton();
        btnAccion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEstudiantes = new javax.swing.JList<>();
        lblResultados = new javax.swing.JLabel();
        lblAdvertencia = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblCarnet = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        lblWarning = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombre.setText("Nombre:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        lblApellido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblApellido.setText("Apellido:");

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("¿Que desea hacer?");

        btngOpciones.add(rbtnAgregar);
        rbtnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtnAgregar.setText("Agregar");
        rbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAgregarActionPerformed(evt);
            }
        });
        rbtnAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbtnAgregarKeyPressed(evt);
            }
        });

        btngOpciones.add(rbtnBuscar);
        rbtnBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtnBuscar.setText("Buscar");
        rbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnBuscarActionPerformed(evt);
            }
        });
        rbtnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbtnBuscarKeyPressed(evt);
            }
        });

        btngOpciones.add(rbtnEditar);
        rbtnEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtnEditar.setText("Editar");
        rbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEditarActionPerformed(evt);
            }
        });
        rbtnEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbtnEditarKeyPressed(evt);
            }
        });

        btngOpciones.add(rbtnEliminar);
        rbtnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtnEliminar.setText("Eliminar");
        rbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEliminarActionPerformed(evt);
            }
        });
        rbtnEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbtnEliminarKeyPressed(evt);
            }
        });

        btnAccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAccion.setText("OK");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstEstudiantes);

        lblAdvertencia.setForeground(new java.awt.Color(255, 255, 255));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setText("salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblCarnet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCarnet.setText("Carnet:");

        txtCarnet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCarnetKeyPressed(evt);
            }
        });

        lblWarning.setForeground(new java.awt.Color(255, 0, 51));
        lblWarning.setText("**CAMPOS INCOMPLETOS**");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(151, 151, 151))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdvertencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblApellido)
                                        .addComponent(lblCarnet))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                        .addComponent(txtCarnet))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbtnEliminar)
                            .addComponent(rbtnEditar)
                            .addComponent(rbtnBuscar)
                            .addComponent(rbtnAgregar)
                            .addComponent(lblResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btnAccion)))
                .addGap(43, 66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellido)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarnet))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWarning)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnEliminar)
                .addGap(4, 4, 4)
                .addComponent(btnAccion)
                .addGap(11, 11, 11)
                .addComponent(lblResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //CERRAR EL DOCUMENTO.
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    //CONTROLAR EL FLUJO A TRAVEZ DE TABS O ENTERS.
    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
        if( evt.getKeyChar() == '\t' || evt.getKeyChar() == '\n'){
            txtApellido.requestFocus();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed
        // TODO add your handling code here:
        if( evt.getKeyChar() == '\t' || evt.getKeyChar() == '\n'){
            if(txtCarnet.isShowing()) txtCarnet.requestFocus();
            else rbtnAgregar.requestFocus();
        }
    }//GEN-LAST:event_txtApellidoKeyPressed

    private void txtCarnetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarnetKeyPressed
        if( evt.getKeyChar() == '\t' || evt.getKeyChar() == '\n'){
            rbtnAgregar.requestFocus();
            rbtnAgregar.doClick();
        }
    }//GEN-LAST:event_txtCarnetKeyPressed

    private void rbtnAgregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtnAgregarKeyPressed
        // TODO add your handling code here:
        if( evt.getKeyChar() == '\t' || evt.getKeyChar() == '\n'){
            rbtnBuscar.requestFocus();
            rbtnBuscar.doClick();
        }
    }//GEN-LAST:event_rbtnAgregarKeyPressed

    private void rbtnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtnBuscarKeyPressed
        // TODO add your handling code here:
        if( evt.getKeyChar() == '\t' || evt.getKeyChar() == '\n'){
            rbtnEditar.requestFocus();
            rbtnEditar.doClick();
        }
    }//GEN-LAST:event_rbtnBuscarKeyPressed

    private void rbtnEditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtnEditarKeyPressed
        // TODO add your handling code here:
        if( evt.getKeyChar() == '\t' || evt.getKeyChar() == '\n'){
            rbtnEliminar.requestFocus();
            rbtnEliminar.doClick();
        }
    }//GEN-LAST:event_rbtnEditarKeyPressed

    private void rbtnEliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtnEliminarKeyPressed
        // TODO add your handling code here:
        if( evt.getKeyChar() == '\t' || evt.getKeyChar() == '\n'){
            btnAccion.requestFocus();
        }
    }//GEN-LAST:event_rbtnEliminarKeyPressed

    //HABILITAR EL CAMPO DE CARNET.
    private void rbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnBuscarActionPerformed
        // TODO add your handling code here:
        txtCarnet.setVisible(true);
        lblCarnet.setVisible(true);
    }//GEN-LAST:event_rbtnBuscarActionPerformed

    private void rbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEditarActionPerformed
        // TODO add your handling code here:
        txtCarnet.setVisible(true);
        lblCarnet.setVisible(true);
    }//GEN-LAST:event_rbtnEditarActionPerformed

    private void rbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEliminarActionPerformed
        // TODO add your handling code here:
        txtCarnet.setVisible(true);
        lblCarnet.setVisible(true);
    }//GEN-LAST:event_rbtnEliminarActionPerformed

    //DESABILITAR EL CAMPO DE CARNET.    
    private void rbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAgregarActionPerformed
        // TODO add your handling code here:
        txtCarnet.setVisible(false);
        lblCarnet.setVisible(false);
    }//GEN-LAST:event_rbtnAgregarActionPerformed

    //REALIZAR ACCION DE RELACION.
    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        // TODO add your handling code here:
        
        //agregar un elemento.
        if( rbtnAgregar.isSelected() ){
                
            //si algun campo esta incompleto.
            if( txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty()){
                lblWarning.setVisible(true);
                return;
            }else{
                lblWarning.setVisible(false);
            }
            
            //asignando valores para ingresar al alumno nuevo
            String Nombre = txtNombre.getText();
            String Apellido = txtApellido.getText();
            String Grado = Integer.toString(Alumno.rel);
            Alumno.rel++;
            
            //agregando alumno.
            Alumno Nuevo = new Alumno(Nombre, Apellido, Grado);
            Control.agregar(Nuevo, dB);
            
            //informando cambio.
            lblResult.setText("Usuario Agregado: " + Nuevo.toString() );
        }
        
        if( rbtnBuscar.isSelected() ){
            //validar si algun campo esta incompleto.
            if( txtCarnet.getText().isEmpty() ){
                lblWarning.setVisible(true);
                return;
            }else{
                lblWarning.setVisible(false);
            }
            
            //buscando resultados
            String Carnet = txtCarnet.getText();
            int target = Control.buscar(Carnet, dB);
            
            
            //presentando resultados.
            if( target == -1){
                lblResult.setText("Resultado de Busqueda: Usuario no encontrado.");
            }else{
                Alumno encontrado = dB.get(target);
                lblResult.setText("Resultado de Busqueda: " + encontrado.toString());
            }
        }
        
        if( rbtnEditar.isSelected() ){
            
            //validando datos.
            if( txtCarnet.getText().isEmpty() ){
                lblWarning.setVisible(true);
                return;
            }else{
                lblWarning.setVisible(false);
            }
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String carnet = txtCarnet.getText();
            
            int target = Control.buscar(carnet, dB);
            
            //presenta y edita la informacion
            if( target == -1 ){
                lblResult.setText( "Usuario no encontrado" );
            }else{
                lblResult.setText( "Cambios Realizados");
                dB.get(target).setNombre(nombre);
                dB.get(target).setApellido(apellido);
            }
        }
        
        if( rbtnEliminar.isSelected() ){
            if( txtCarnet.getText().isEmpty() ){
                lblWarning.setVisible(true);
                return;
            }else{
                lblWarning.setVisible(false);
            }
            String carnet = txtCarnet.getText();
            if(Control.eliminar(carnet, dB)){
                lblResult.setText("Usuario Eliminado");
            }else{
                lblResult.setText("Usuario no encontrado");
            }
        }
        
        //reordena informacion obtenida.
        Control.ordenar(dB);
        int size = dB.size();
        //JOptionPane.showMessageDialog(null, size);
        
        //reimprime la informacion.
        DefaultListModel dB_String = new DefaultListModel();
        for(int i = 0; i < size; i++){
            dB_String.addElement( dB.get(i).toString() );
        }
        
        lstEstudiantes.setModel(dB_String);
        
    }//GEN-LAST:event_btnAccionActionPerformed
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup btngOpciones;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdvertencia;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCarnet;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblResultados;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JList<String> lstEstudiantes;
    private javax.swing.JRadioButton rbtnAgregar;
    private javax.swing.JRadioButton rbtnBuscar;
    private javax.swing.JRadioButton rbtnEditar;
    private javax.swing.JRadioButton rbtnEliminar;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
